"""initial schema

Revision ID: 4ec51ed618df
Revises: 
Create Date: 2026-01-26 13:35:33.173008
"""

from alembic import op
import sqlalchemy as sa

revision = '4ec51ed618df'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internet_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('mikrotik_profile', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('malls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], name='fk_routers_mall_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], name='fk_users_mall_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_mall_id'), ['mall_id'], unique=False)

    op.create_table('payments.py',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['internet_packages.id'], name='fk_payments_package_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_payments_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['internet_packages.id'], name='fk_subscriptions_package_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_subscriptions_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('payments.py')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mall_id'))
        batch_op.drop_index(batch_op.f('ix_users_mac_address'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    op.drop_table('routers')
    op.drop_table('malls')
    op.drop_table('internet_packages')
    # ### end Alembic commands ###
