"""add vouchers

Revision ID: 66dda0613bb9
Revises: 4ec51ed618df
Create Date: 2026-01-26 14:03:53.352926
"""

from alembic import op
import sqlalchemy as sa

revision = '66dda0613bb9'
down_revision = '4ec51ed618df'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
